version: '2'

services:

  web:
    build:
      context: .docker/nginx
    volumes:
    - ./:/var/www
    ports:
    - "9080:80"

  app:
    build:
      context: .docker/php
      args:
        PUID: "1000"
        # PHP_INSTALL_XDEBUG: "false"
        # INSTALL_GIT: "true"
        # PHP_XDEBUG_PORT: "9000"
    volumes:
    - ./:/var/www
    environment:
    - "POSTGRES_HOST=database"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_PASSWORD=postgres"
    - "POSTGRES_DB=example"
    - "PHP_IDE_CONFIG=serverName=localhost"
    user: www-data
#    extra_hosts:
#    - "dockerhost:10.0.75.1"

#  database:
#    image: postgres:10-alpine
#    environment:
#    - "POSTGRES_DB=example"
#    - "POSTGRES_USER=postgres"
#    - "POSTGRES_PASSWORD=postgres"
#    ports:
#    - "5432:5432"
#
#  redis:
#    image: redis:4.0.2
#    ports:
#    - "6379:6379"